export let config = {
    "token" : "",
    "version" : "1.1.0",
    "prefix" : "?",
    "locked" : false,
    "cooldown": true,
    "raphid" : "445787036197060610",
    "settingcommands" : [
        "botinfo",
        "help",
        "prefix",
        "stop",
        "suggest",
        "talk",
        "test",
    ],
    "commands" : [
        "buy",
        "craft",
        "fight",
        "gamble",
        "info",
        "leaderboard",
        "pocket",
        "scavenge",
        "sell",
        "shop",
        "stocks",
        "throw",
        "travel",
        "use",
    ],
};